[package]
name = "obs-cmd"
version = "0.1.1"
edition = "2021"
description = "A minimal command to control obs via obs-websocket"
authors = ["Luigi Maselli <luigi@grigio.org>"]
rust-version = "1.70.0"

[[bin]]
name = "obs-cmd"

[dependencies]
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros"] }
obws = "0.11.0"
clap = { version = "4.4.8", features = ["derive"] }
url = "2.4.1"
